spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 284104548
    url: jdbc:mysql://localhost:3306/2007-food?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

  #redis
  redis:
    host: 192.168.130.128


    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

server:
  port: 80

mybatis-plus:
  global-config:
    db-config:
      tablePrefix: oa_

logging:
  config: classpath:logback-spring.xml
  level:
    root: error

