spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xxxxxxxxxxx
    url: jdbc:mysql://localhost:3306/xxxxxxxxxxx?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#  data:
#    mongodb:
#      uri: mongodb://192.168.130.128:27017/2007A


  #redis
  redis:
    host: xxxxxxxxxxxxx




#  servlet:
#    multipart:
#      max-file-size: 2MB
#      max-request-size: 20MB

server:
  port: 80

mybatis-plus:
  global-config:
    db-config:
      tablePrefix: oa_

logging:
  config: classpath:logback-spring.xml
  level:
    root: debug

